create database college_id;
use college_id;
create table students(std_id int primary key auto_increment, Std_name varchar(100) not null, email varchar(50) unique not null, age int check(age>=18),city varchar(50) default 'Kochi');
insert into students(std_name, email, age, city) values ("Rithu","rithu@gmail.com",24,"Mumbai"),("Akshay","akshay@gmail.com",23,"Kochi"),("Keerthy","keerthy@gmail.com",21,"Kollam"),("Anu","anu@g,ail.com",25,"Chennai"),("Rahul","rahul@gmail.com",24,"Kochi");
select *  from students;
insert into students(email,age,city) values("gokul@gmail.com",25,"Chennai");
insert into students(std_name,email,age,city) values("Rithu",24,"Mumbai");
insert into students(std_name,email,age) values("Akshay","akshay@gmail.com",18,"Kochi");
create table course(course_id int primary key auto_increment, course_name varchar(50), duration int);
insert into course(course_name,duration) values("MBA",2),("MCOM",2),("Data Analytics",3);
select * from course;
alter table course add dept varchar(50);
alter table course drop column duration;
create table enrollement(emt_id int primary key auto_increment,std_id int not null, course_id int not null, foreign key(std_id) references students(std_id),foreign key(course_id) references course(course_id));
insert into enrollement(std_id,course_id) values(1,1),(1,2),(2,1),(3,3);
select * from enrollement;
insert into enrollement(std_id,course_id) values(10,5);
insert into enrollement(std_id,course_id) values(2,5);
select std_name, age from students;
set foreign_key_checks=0;
truncate table course;
set foreign_key_checks=1;
set foreign_key_checks=0;
drop table course;
set foreign_key_checks=1;