create database product;
use product;
create table sales(order_id int primary key auto_increment,region varchar(50),prct varchar(50),amt int);
insert into sales(region,prct,amt) values("Kochi","mobile",24000),("Kollam","laptop",20000),("Trivandrum","Mouse",10000),("Thrissurr","tablet",26000);
select * from sales;
select region, sum(amt) as total_sales from sales group by region;
select prct, avg(amt) as avg_sales from sales group by prct;
select region, sum(amt) as total_sales from sales group by region having sum(amt>100000);
select prct, avg(amt) as avg_sales from sales group by prct having avg(amt)>10000;
create table customer(cust_id int,cust_name varchar(50));
insert into customer(cust_id,cust_name) values(101,"Rithu"),(102,"Akki"),(103,"Afin"),(104,"Keerthy");
select * from customer;
create table orders(order_id int,cust_id int,order_amt int);
insert into orders(order_id,cust_id,order_amt) values(1000,101,30000),(1001,102,25000),(1002,103,26000),(1003,104,23000);
select * from orders;
select c.cust_name,o.order_id,o.order_amt from customer c inner join orders o on c.cust_id=o.order_id;
select c.cust_name,o.order_id,o.order_amt from customer c inner join orders o on c.cust_id=o.cust_id where o.order_amt>4000;
create table employee(emp_id int primary key auto_increment,emp_name varchar(50),dept_id int, salary int, join_date date);
insert into employee(emp_name,dept_id,salary,join_date)values("Dhiya",001,60000,'2002-10-20'),("Rithu",002,55000,'2003-06-04'),(null,003,45000,'2002-07-01');
select * from employee;
create table dept(dept_id int,dept_name varchar(50));
insert into dept(dept_id,dept_name) values(001,"HR"),(002,"Finance"),(003,"IT");
select * from dept;
select e.emp_id,e.emp_name,e.dept_id,d.dept_name from employee e left join dept d on e.dept_id=d.dept_id;
select e.emp_id,e.emp_name,e.dept_id,d.dept_name from employee e left join dept d on e.dept_id=d.dept_id where d.dept_id=null;
select emp_name from employee where dept_id in (001,002) union select emp_name from employee where dept_id in(002,003);
select emp_name from employee where dept_id in (001,002) union all select emp_name from employee where dept_id in(002,003);
truncate table employee;
create table employee_fn(emp_id int primary key auto_increment, first_name varchar(50),last_name varchar(50),salary int, joining_date date);
insert into employee_fn(first_name,last_name,salary,joining_date) values("Rithu","M",25000,'2026-10-01'),("Akki",'P',30000,'2026-12-20'),("Keerthy","M",26000,'2025-04-28');
select * from employee_fn;
select emp_id, concat(first_name,' ',last_name)as full_name from employee_fn;
select emp_id, salary, round(salary) as round_salary from employee_fn;
select emp_id, salary, abs(salary) as absolute_salary from employee_fn;
select emp_id, first_name,datediff(curdate(),joining_date) as exp_days from employee_fn;
select emp_id, last_name, left(last_name,3)as new_lstname from employee_fn;
alter table employee drop column join_date;
select avg(salary)from employee;
select emp_id,emp_name,salary from employee where salary>(select avg(salary) from employee);
select emp_id, emp_name,dept_id from employee where dept_id in (select dept_id from dept where dept_name in ('HR','IT'));
select max(salary) from employee;
select emp_id,emp_name from employee where salary=(select max(salary) from employee);
create view employee_report as select e.emp_name as Name, d.dept_name as Department, e.salary as Salary from employee e left join dept d on e.dept_id=d.dept_id;
select * from employee_report;
select * from employee_report where salary>25000;