create database info;
use info;
create table students(std_id int primary key auto_increment,std_name varchar(50),email varchar(50),age int,dept varchar(50));
insert into students(std_name,email,age,dept) values("Keerthy","keerthy@gmail.com",24,"Operations"),("Anu","anu@gmail.com",22,"Finance"),("Rithu","rithu@gmail.com",25,"HR"),("Amitha","amitha@gmail.com",23,"HR"),("Devika","devika@gmail.com",24,"Finance");
select * from students;
create table customer(cust_id int primary key auto_increment, cust_FN varchar(50),cust_mail varchar(50), purchase_amt int);
insert into customer(cust_FN,cust_LN,cust_mail,purchase_amt) values("Akshay","P","akshay@gmail.com",50000),("Rahul","M","rahul@gmail.com",60000),("Afin","J","afin@gmail.com",70000);
select * from customer;
alter table customer add column cust_LN varchar(50);
create table sales(order_id int primary key auto_increment,cust_id int,product varchar(50),quantity int,amount int);
insert into sales(cust_id,product,quantity,amount) values(1,"mobiles",25,25000),(5,"laptop",15,30000),(3,"mouse",10,20000);
select * from sales;
update students set dept='operation' where std_id=2;
update students set age=23,dept="finance" where std_id=3;
delete from students where std_id=1;
delete from students where age<20;
select distinct dept as dept_name from students where age>18;
select * from students where age between 18 and 22;
select * from students where dept in ('hr','finance');
select * from students where email is null;
select std_name from students where std_name like '%an%';
select cust_FN as fname from customer;
select * from customer order by cust_LN;
select * from customer order by purchase_amt limit 5;
select count(order_id)as total_sales from sales;
select sum(amount) as total_revenue from sales;
select min(amount) as min_amount from sales;
select max(amount) as max_amount from sales;
delete from students;
truncate table students;
drop table students;